repos:
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.8
      stages: [commit]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      stages: [commit]
-   repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v -s
        always_run: true
        pass_filenames: false
        stages: [commit]